import { Project, Experience, Skill } from './types';

export const skills: Skill[] = [
  { name: 'Java' },
  { name: 'Spring Boot' },
  { name: 'Spring Batch' },
  { name: 'Spring' },
  { name: 'Python' },
  { name: 'PHP' },
  { name: 'JavaScript' },
  { name: 'Scala' },
  { name: 'React' },
  { name: 'Redux' },
  { name: 'HTML & CSS' },
  { name: 'Material UI' },
  { name: 'Ag-Grid' },
  { name: 'Apex Charts' },
  { name: 'Apache Kafka' },
  { name: 'Redis' },
  { name: 'MySQL' },
  { name: 'MongoDB' },
  { name: 'PostgreSQL' },
  { name: 'Hive' },
  { name: 'Protobuf' },
  { name: 'ANTLR' },
  { name: 'Android' },
  { name: 'AWS' },
  { name: 'Docker' },
  { name: 'Kubernetes' },
  { name: 'Azkaban' },
  { name: 'Jenkins' },
  { name: 'Git' },
  { name: 'Jira' },
  { name: 'Bitbucket' },
  { name: 'Junit' },
  { name: 'Mockito' },
  { name: 'SonarQube' },
  { name: 'Taurus' },
  { name: 'Postman' },
  { name: 'MySQL Workbench' },
  { name: 'IntelliJ IDEA' },
  { name: 'Kibana' },
  { name: 'Hadoop' },
  { name: 'Sqoop' },
  { name: 'Beeline' },
  { name: 'Redis Desktop Manager' },
  { name: 'Localstack' },
  { name: 'Shell' },
  { name: 'Agile & Scrum' },
];

export const experiences: Experience[] = [
  {
    period: '2023 Jan – Present',
    location: 'Singapore',
    role: 'Software Engineer',
    company: 'Rakuten',
    companyInfo: 'Japan\'s largest internet company and largest e-commerce platform in Japan.',
    highlights: [
      'Leveraged AI tools professionally for code generation, optimization, and accelerated feature development to increase productivity',
      'Developed and maintained web applications using Java, Spring, and MySQL with high availability requirements',
      'Built internal APIs and batch applications leveraging Spring Boot, Scala, Hive, MongoDB, and MySQL for large-scale data processing',
      'Developed Spring Batch jobs for large-scale data processing and transformation across enterprise systems',
      'Deployed and scheduled batch jobs using Azkaban for efficient pipeline management handling millions of transactions',
      'Created automation scripts and support tools using Shell and Python to streamline development and operations',
      'Enhanced code quality by integrating SonarQube and performed performance testing with Taurus for production-grade systems',
      'Designed and managed database schemas, ensuring data integrity and operational efficiency for high-traffic platforms',
      'Handled live issue resolution, ensuring consistent application stability and uptime across services',
    ],
  },
  {
    period: '2021 Jan – 2022 Dec',
    location: 'Singapore',
    role: 'Software Engineer',
    company: 'ZeroBeta',
    companyInfo: 'High-performance computing platform specializing in financial risk management solutions.',
    highlights: [
      'Developed and maintained modern applications using Java, Spring Boot, and MySQL for production financial systems',
      'Designed and implemented frontend features with React, Ag-Grid, Apex-charts, Material-UI, and Redux for complex data visualization',
      'Integrated caching solutions with Redis and implemented message passing via Kafka for real-time data processing',
      'Improved and maintained code quality through SonarQube integration and continuous improvement practices',
      'Conducted requirements gathering, POC development, technical feasibility analysis, and performance impact assessments',
      'Provided live issue resolution to support application stability and production environment reliability',
    ],
  },
  {
    period: '2020 Feb – 2021 Jan',
    role: 'Software Engineer',
    company: 'Information Systems Associates (AccelAero)',
    companyInfo: 'Leading provider of advanced technology solutions for the global travel and aviation industry.',
    highlights: [
      'Developed modern applications using Java, Spring Boot, Protobuf, ANTLR, and PostgreSQL for aviation systems',
      'Contributed to frontend development with React and Redux for complex domain-specific applications',
      'Implemented APIs and business logic, ensuring high JUnit test coverage and maintaining code quality through SonarQube',
      'Utilized Jira for sprint management and Bitbucket for version control in an Agile environment',
    ],
  },
  {
    period: 'Personal',
    location: 'Ongoing',
    role: 'Builder',
    company: 'CCMTS · Algo Trading',
    companyInfo: 'Personal high-frequency trading system with live execution across multiple exchanges.',
    highlights: [
      'Built live trading system with <10ms signal-to-order latency (Binance, IBKR, Alpaca)',
      'Real-time market microstructure analysis (OBI, VPIN, Hurst exponent indicators)',
      'Walk-forward backtesting framework with XGBoost machine learning signals',
      'Multi-leg position management and portfolio rebalancing',
    ],
    isPersonal: true,
  },
];

export const projects: Project[] = [
  {
    id: 'ccmts',
    name: 'CCMTS',
    description: 'Live algo trading system with sub-10ms signal-to-order latency. Multi-exchange support with real-time market microstructure analysis.',
    category: 'trading',
    status: 'complete',
    metrics: [
      { value: '<10ms', label: 'Signal-to-order' },
      { value: '3', label: 'Exchanges' },
    ],
    technologies: ['Java 21', 'Chronicle Queue', 'XGBoost', 'WebSocket'],
  },
  // Add more projects here as you build them
];

// Get only completed projects for display
export const completedProjects = projects.filter((p) => p.status === 'complete');
